export const PERMISSIONS = {

  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  CLIENTS_VIEW: 'CLIENTS_VIEW',
  CLIENTS_CREATE: 'CLIENTS_CREATE',
  CLIENTS_EDIT: 'CLIENTS_EDIT',
  CLIENTS_DELETE: 'CLIENTS_DELETE',

  COLLECTORS_VIEW: 'COLLECTORS_VIEW',
  COLLECTORS_CREATE: 'COLLECTORS_CREATE',
  COLLECTORS_EDIT: 'COLLECTORS_EDIT',
  COLLECTORS_DELETE: 'COLLECTORS_DELETE',

  SUPERVISORS_VIEW: 'SUPERVISORS_VIEW',
  SUPERVISORS_CREATE: 'SUPERVISORS_CREATE',
  SUPERVISORS_EDIT: 'SUPERVISORS_EDIT',
  SUPERVISORS_DELETE: 'SUPERVISORS_DELETE',

  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE',

  ROLES_VIEW: 'ROLES_VIEW',
  ROLES_ASSIGN_PERMISSIONS: 'ROLES_ASSIGN_PERMISSIONS',

  OWNERS_VIEW: 'OWNERS_VIEW',
  OWNERS_CREATE: 'OWNERS_CREATE',
  OWNERS_EDIT: 'OWNERS_EDIT',
  OWNERS_DELETE: 'OWNERS_DELETE',

  ZONES_VIEW: 'ZONES_VIEW',
  ZONES_CREATE: 'ZONES_CREATE',
  ZONES_EDIT: 'ZONES_EDIT',
  ZONES_DELETE: 'ZONES_DELETE',

  CREDITS_VIEW: 'CREDITS_VIEW',
  CREDITS_CREATE: 'CREDITS_CREATE',
  CREDITS_EDIT: 'CREDITS_EDIT',
  CREDITS_DELETE: 'CREDITS_DELETE',

  PLAN_TYPES_VIEW: 'PLAN_TYPES_VIEW',
  PLAN_TYPES_CREATE: 'PLAN_TYPES_CREATE',
  PLAN_TYPES_EDIT: 'PLAN_TYPES_EDIT',
  PLAN_TYPES_DELETE: 'PLAN_TYPES_DELETE',

  HOLIDAYS_VIEW: 'HOLIDAYS_VIEW',
  HOLIDAYS_CREATE: 'HOLIDAYS_CREATE',
  HOLIDAYS_EDIT: 'HOLIDAYS_EDIT',
  HOLIDAYS_DELETE: 'HOLIDAYS_DELETE',

  VALES_VIEW: 'VALES_VIEW',
  VALES_CREATE: 'VALES_CREATE',
  VALES_EDIT: 'VALES_EDIT',
  VALES_DELETE: 'VALES_DELETE',

  AYUDAS_VIEW: 'AYUDAS_VIEW',
  AYUDAS_CREATE: 'AYUDAS_CREATE',
  AYUDAS_EDIT: 'AYUDAS_EDIT',
  AYUDAS_DELETE: 'AYUDAS_DELETE'

}